name: Build and deploy Node.js app to Azure Web App - draftbash-test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Generate .env file
        run: |
          echo "DB_PASSWORD=${{ secrets.PRODUCTION_DB_PASSWORD }}" > .env
          echo "DB_USER=stephenpfeddes" >> .env
          echo "DB_HOST=ep-weathered-wind-21075129-pooler.us-east-2.aws.neon.tech" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_NAME=neondb" >> .env
          echo "SSL=true" >> .env

      - name: npm install, build, and test
        run: |
          npm ci
          npm install -g typescript
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'draftbash-test'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_14D3C38EC8DD47998C85699A2D026B41 }}
          package: .